apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-nov29-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-nov29-1:cc1fa58e3eab164a67ad5cd425e8df46e04fdda2@sha256:19752dc31681695c38843ed129ae004362a068d2ceabcc35273f8d6d35de9f5a # use pre-built to bootstrap 
          name: app-inference
